FROM bellsoft/liberica-openjdk-alpine:21
WORKDIR /selenium-docker
ADD c:/User/manik/selenium-docker/target/docker-resources ./

#ENTRYPOINT java --version
	
	#-cp 'libs/*' org.testng.TestNG test-suites/vendor-portal.xml
	
	