services:
  hub:
    image: "selenium/hub:latest"
    ports:
     - 4444:4444
  chrome:
    image: selenium/node-chrome:latest
    shm_size: '1g'
    depends_on:
    - hub
    environment:
    - SE_EVENT_BUS_HOST=hub
    - SE_EVENT_BUS_PUBLISH_PORT=4442
    - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    - SE_NODE_OVERRIDE_mAX_SESSIONS=true
    - SE_NODE_MAX_SESSIONS=1
  firefox:
    image: selenium/node-firefox:latest
    shm_size: '1g'
    depends_on:
    - hub
    environment:
    - SE_EVENT_BUS_HOST=hub
    - SE_EVENT_BUS_PUBLISH_PORT=4442
    - SE_EVENT_BUS_SUBSCRIBE_PORT=4443  
    - SE_NODE_OVERRIDE_mAX_SESSIONS=true  
    - SE_NODE_MAX_SESSIONS=1
    - SE_VNC_NO_PASSWORD=1
  vendor-portal:
    image: rockermani/testonjenkins
    depends_on:
    - chrome
    environment:
    - BROWSER=chrome
    - HUB_HOST=hub
    - THREAD_COUNT=1
    - TEST_SUITE=vendor-portal.xml
    volumes:
    - ./output/vendor-portal:/home/selenium-docker/test-output 
  flight-reservation:
    image: rockermani/testonjenkins
    depends_on:
    - chrome
    environment:
    - BROWSER=chrome
    - HUB_HOST=hub
    - THREAD_COUNT=1
    - TEST_SUITE=flight-reservation.xml
    volumes:
    - ./output/flight-reservation:/home/selenium-docker/test-output     