services:
  hub:
    image: "selenium/hub:latest"
    ports:
     - 4444:4444
     - 4442:4443
     - 4443:4443
  chrome:
    image: selenium/node-chrome:latest
    shm_size: '2g'
    depends_on:
    - hub
    environment:
    - SE_EVENT_BUS_HOST=hub
    - SE_EVENT_BUS_PUBLISH_PORT=4442
    - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    - SE_NODE_OVERRIDE_mAX_SESSIONS=true
    - SE_NODE_MAX_SESSIONS=2
    - SE_VNC_PASSWORD=mani@123
  firefox:
    image: selenium/node-firefox:latest
    shm_size: '2g'
    depends_on:
    - hub
    environment:
    - SE_EVENT_BUS_HOST=hub
    - SE_EVENT_BUS_PUBLISH_PORT=4442
    - SE_EVENT_BUS_SUBSCRIBE_PORT=4443  
    - SE_NODE_OVERRIDE_mAX_SESSIONS=true  
    - SE_NODE_MAX_SESSIONS=4
    - SE_VNC_NO_PASSWORD=1